### ISSUE TITLE
fix server side redirects

### ISSUE THREAD

**Issue by erichulburd** [arbolista-dev/generator-spike#11]
React router redirects will be caught by `renderReact`, but this is currently leading to infinite redirect.

Recreate issue:
- run `ISOMORPHIC=1 npm run dev`.
- navigate to `/`. Login. Refresh page.

We can take `redirect` from `renderReact` and apply it like so on server:

```
      if (redirect) {
        const { url, status } = redirect;
        res.redirect(status, url);
        return;
      }
```

**Comment by daruj** [comment]
fixed in https://github.com/arbolista-dev/generator-spike/pull/13
