### ISSUE TITLE
Redux storage is not loading redux state from cookies

### ISSUE THREAD

**Issue by erichulburd** [arbolista-dev/generator-spike#12]
We are using:
- https://www.npmjs.com/package/redux-storage
- https://www.npmjs.com/package/redux-storage-engine-cookies

However, redux is not being initialized with browser cookie values.

We should also make sure that the server is properly reading cookies for server side rendering.

**Comment by daruj** [comment]
fixed in https://github.com/arbolista-dev/generator-spike/pull/13
